<a href="https://colab.research.google.com/github/siriMallika/BasicMachineLearning/blob/master/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import sklearn

print(pd.__version__)
print(np.__version__)
print(sklearn.__version__)

0.23.4
1.15.4
0.20.1


In [0]:
from sklearn import datasets
iris  = datasets.load_iris()
print('Data: ')
print(iris['data'].shape)
print('Target: ')
print(iris['target'].shape)

Data: 
(150, 4)
Target: 
(150,)


In [0]:
print('Sample of Data')
print(iris['data'][0:5])
print('Sample of Target')
print(iris['target'][0:5])

Sample of Data
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Sample of Target
[0 0 0 0 0]


In [0]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(iris['data'],iris['target'])
from sklearn.model_selection import cross_val_score
cross_val_score(model, iris['data'], iris['target'], cv=10)

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.86666667, 0.93333333, 1.        , 1.        , 1.        ])

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris['data'],
iris['target'],test_size = 0.3)
model_2 = DecisionTreeClassifier()
model_2.fit(x_train,y_train)

from sklearn.metrics import accuracy_score

y_pred = model_2.predict(x_train)
print('Accuracy of Training set: ')
print(accuracy_score(y_train,y_pred))

y_pred = model_2.predict(x_test)
print('Accuracy of Test set: ')
print(accuracy_score(y_test,y_pred))

Accuracy of Training set: 
1.0
Accuracy of Test set: 
0.9555555555555556


In [0]:
!pip install mlxtend

  Using cached https://files.pythonhosted.org/packages/16/e6/30e50ed9c053a1530c83149090e1f5fd9fccc8503dca2ecce1bb52f34de0/mlxtend-0.15.0.0-py2.py3-none-any.whl


In [0]:
dataset = [['Milk','Orion','Nutmeg','Kidney Beans','Eggs','Yogurt'],
           ['Dill','Onion','Nutmeg','Kidney Beans','Eggs','Yogurt'],
           ['Milk','Apple', 'Kidney Beans' ,'Eggs'],
           ['Milk','Unicorn','Corn','Kidney Beans','Yogurt'],
           ['Corn','Onion','Onion','Kidney Beans','Ice cream' ,'Eggs']
          ]
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary,columns=te.columns_)
df

Apple   Corn   Dill   Eggs  Ice cream  Kidney Beans   Milk  Nutmeg  Onion  \
0  False  False  False   True      False          True   True    True  False   
1  False  False   True   True      False          True  False    True   True   
2   True  False  False   True      False          True   True   False  False   
3  False   True  False  False      False          True   True   False  False   
4  False   True  False   True       True          True  False   False   True   

   Orion  Unicorn  Yogurt  
0   True    False    True  
1  False    False    True  
2  False    False   False  
3  False     True    True  
4  False    False   False

In [0]:
from mlxtend.frequent_patterns import apriori
apriori(df,min_support = 0.6)

support itemsets
0      0.8      (3)
1      1.0      (5)
2      0.6      (6)
3      0.6     (11)
4      0.8   (3, 5)
5      0.6   (5, 6)
6      0.6  (11, 5)

In [0]:
apriori(df,min_support = 0.6,use_colnames=True)

support                itemsets
0      0.8                  (Eggs)
1      1.0          (Kidney Beans)
2      0.6                  (Milk)
3      0.6                (Yogurt)
4      0.8    (Kidney Beans, Eggs)
5      0.6    (Kidney Beans, Milk)
6      0.6  (Yogurt, Kidney Beans)

In [0]:
import pandas as pd
dataset2 = []
dataset = pd.read_csv('GroceryStoreDataSet.csv',header=None)
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
dataset =  dataset.values
for i in dataset:
    for j in i:
        result = j.split(',')
#         print(result)
    dataset2.append(result)
      
# print(dataset2)
te_ary = te.fit(dataset2).transform(dataset2)
df = pd.DataFrame(te_ary,columns=te.columns_)
df

BISCUIT  BOURNVITA  BREAD   COCK  COFFEE  CORNFLAKES    JAM  MAGGI   MILK  \
0      True      False   True  False   False       False  False  False   True   
1      True      False   True  False   False        True  False  False   True   
2     False       True   True  False   False       False  False  False  False   
3     False      False   True  False   False       False   True   True   True   
4      True      False  False  False   False       False  False   True  False   
5     False       True   True  False   False       False  False  False  False   
6     False      False  False  False   False        True  False   True  False   
7      True      False   True  False   False       False  False   True  False   
8     False      False   True  False   False       False   True   True  False   
9     False      False   True  False   False       False  False  False   True   
10     True      False  False   True    True        True  False  False  False   
11     True      False  False   True    True        True  False  False  False   
12    False       True  False  False    True       False  False  False  False   
13    False      False   True   True    True       False  False  False  False   
14     True      False   True  False   False       False  False  False  False   
15    False      False  False  False    True        True  False  False  False   
16    False       True   True  False   False       False  False  False  False   
17    False      False   True  False    True       False  False  False  False   
18    False      False   True  False    True       False  False  False  False   
19    False      False  False  False    True        True  False  False   True   

    SUGER    TEA  
0   False  False  
1   False  False  
2   False   True  
3   False  False  
4   False   True  
5   False   True  
6   False   True  
7   False   True  
8   False   True  
9   False  False  
10  False  False  
11  False  False  
12   True  False  
13  False  False  
14   True  False  
15   True  False  
16   True  False  
17   True  False  
18   True  False  
19  False   True

In [0]:
dataset2 = []

['MILK', 'BREAD', 'BISCUIT']
['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES']
['BREAD', 'TEA', 'BOURNVITA']
['JAM', 'MAGGI', 'BREAD', 'MILK']
['MAGGI', 'TEA', 'BISCUIT']
['BREAD', 'TEA', 'BOURNVITA']
['MAGGI', 'TEA', 'CORNFLAKES']
['MAGGI', 'BREAD', 'TEA', 'BISCUIT']
['JAM', 'MAGGI', 'BREAD', 'TEA']
['BREAD', 'MILK']
['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES']
['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES']
['COFFEE', 'SUGER', 'BOURNVITA']
['BREAD', 'COFFEE', 'COCK']
['BREAD', 'SUGER', 'BISCUIT']
['COFFEE', 'SUGER', 'CORNFLAKES']
['BREAD', 'SUGER', 'BOURNVITA']
['BREAD', 'COFFEE', 'SUGER']
['BREAD', 'COFFEE', 'SUGER']
['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']


In [0]:
from mlxtend.frequent_patterns import apriori
apriori(df,min_support = 0.1, use_colnames=True)

support                             itemsets
0      0.35                            (BISCUIT)
1      0.20                          (BOURNVITA)
2      0.65                              (BREAD)
3      0.15                               (COCK)
4      0.40                             (COFFEE)
5      0.30                         (CORNFLAKES)
6      0.10                                (JAM)
7      0.25                              (MAGGI)
8      0.25                               (MILK)
9      0.30                              (SUGER)
10     0.35                                (TEA)
11     0.20                     (BISCUIT, BREAD)
12     0.10                      (BISCUIT, COCK)
13     0.10                    (BISCUIT, COFFEE)
14     0.15                (BISCUIT, CORNFLAKES)
15     0.10                     (BISCUIT, MAGGI)
16     0.10                      (BISCUIT, MILK)
17     0.10                       (BISCUIT, TEA)
18     0.15                   (BREAD, BOURNVITA)
19     0.10                   (SUGER, BOURNVITA)
20     0.10                     (TEA, BOURNVITA)
21     0.15                      (COFFEE, BREAD)
22     0.10                         (JAM, BREAD)
23     0.15                       (BREAD, MAGGI)
24     0.20                        (MILK, BREAD)
25     0.20                       (SUGER, BREAD)
26     0.20                         (TEA, BREAD)
27     0.15                       (COFFEE, COCK)
28     0.10                   (CORNFLAKES, COCK)
29     0.20                 (CORNFLAKES, COFFEE)
30     0.20                      (SUGER, COFFEE)
31     0.10                   (MILK, CORNFLAKES)
32     0.10                    (CORNFLAKES, TEA)
33     0.10                         (JAM, MAGGI)
34     0.20                         (TEA, MAGGI)
35     0.10               (BISCUIT, BREAD, MILK)
36     0.10              (BISCUIT, COFFEE, COCK)
37     0.10          (BISCUIT, CORNFLAKES, COCK)
38     0.10        (BISCUIT, CORNFLAKES, COFFEE)
39     0.10                (BISCUIT, TEA, MAGGI)
40     0.10              (TEA, BREAD, BOURNVITA)
41     0.10               (COFFEE, SUGER, BREAD)
42     0.10                  (JAM, BREAD, MAGGI)
43     0.10                  (TEA, BREAD, MAGGI)
44     0.10           (CORNFLAKES, COFFEE, COCK)
45     0.10  (BISCUIT, CORNFLAKES, COFFEE, COCK)